title: ShardaLearningCenter
email: s.learnkarma@gmail.com
description: >- 
  Learn to code by building real projects. Fast. Practical. No fluff.
baseurl: "" 
url: "shaardalearningcenter.github.io" 
theme: minima
plugins:
  - jekyll-feed
# ðŸ‘‡ Add this to show menu in navbar
minima:
  skin: auto
  social_links: []
  navigation:
    - title: "Home"
      url: "/"
    - title: "Python Bootcamp"
      url: "/python-bootcamp/"
    - title: "About"
      url: "/about/"